### ISSUE TITLE
UserLAnd Entering Illegal State: Can't change directory to '/'

### ISSUE THREAD

**Issue by Procambarus-gracilis** [CypherpunkArmory/UserLAnd#1003]
I recently had to do an Android security upgrade and after having done so, trying to start UserLAnd would just result in a perpetual wait upon trying to launch Debian (I was using the desktop version via VNC).  I uninstalled the app, re-installed, cleared the support files, but UserLAnd will not work anymore.  When I try re-installing it fresh, I get an error indicating that UserLAnd cannot change directory to '/.'

Looking through the archives, I have not seen this issue resolved.  Would someone please tell me if there is hope to have to have this fixed at some point?

My machine is a Samsung Galaxy Tab E running Android 8.1.0.  Thanks.

**Comment by stephenprater** [comment]
@Procambarus-gracilis I believe we released a bug-fix for this today.  Can you try version 2.6.2?

**Comment by Procambarus-gracilis** [comment]
I've installed version 2.6.2 but I still get the same error about UserLand entering an illegal state when trying to unzip a tar ball as part of the initial installation process.  Thanks.

Sent from Outlook
________________________________

**Comment by corbinlc** [comment]
@Procambarus-gracilis we have fixed this issue.  You can see the conversation on #1014.  A new version was released today v2.6.3 (might be a few hours until you see the option to update).
