### ISSUE TITLE
silent crash caused by RAM usage

### ISSUE THREAD

**Issue by ThinkOpenly** [CypherpunkArmory/UserLAnd#154]
I'm using Debian, installed qemu-system-ppc, and trying to install Debian as a full-system emulated ppc64le environment.  A couple hours in, the session goes away completely, so I suspect a crash, but there is no other evidence.  What information shall I collect? I can turn on logging, I believe, but what level of logging is recommended?

**Comment by AdamMatthewLTM** [comment]
@ThinkOpenly ,

This may also be a duplicate of issue #140 , please see that thread for more information. If it is a direct duplicate I will recommend this one be closed and direct everyone else to #140 .

**Comment by ThinkOpenly** [comment]
Definitely repeatable. I hit it every time, about 3 times in a row.  I will gather debug log.

**Comment by ThinkOpenly** [comment]
I got it to succeed.  I had been using this command:
```
qemu-system-ppc64 -machine pseries,accel=tcg -m 2048 -cdrom ./debian-9.4.0-ppc64el-netinst.iso -hda ./debian-ppc64.qcow2 -display vnc=:12
```
Then I thought, hey, how much memory do I have with UserLAnd?
```
$ head -1 /proc/meminfo
MemTotal:        3731476 kB
```
Only about 3.5 GB.  So, I enabled the debug log, and also reduced the memory requested:
```
qemu-system-ppc64 -machine pseries,accel=tcg -m 1536 -cdrom ./debian-9.4.0-ppc64el-netinst.iso -hda ./debian-ppc64.qcow2 -display vnc=:12
```
... and things worked!

Questions:
1. How does UserLAnd decide how much memory to give to its sessions?
1. Can this be changed?
1. Is it worth pursuing the original issue where it crashed very likely due to running out of memory?  (I'm thinking not.)

**Comment by AdamMatthewLTM** [comment]
@ThinkOpenly ,

Thanks for figuring this out! So let me make this response a two-parter, with part one being a recommendation along with some details, and part two being answers to your questions.

Part One:

Because this is a memory/resource management issue, I will edit the above response and no longer link this to the previous issue I mentioned earlier. I am recommending this thread remain open until further notice, because this is the first direct correlation between memory usage and crashes I have seen thus far. If possible I'd also like to request an update the title of the issue filed to something more comprehensive such as "silent crash caused by RAM usage", something along those lines. Let me know if you think this is appropriate.

Part Two:

1. How does UserLAnd decide how much memory to give to its sessions?

a: will update this response once an accurate explanation is given.

2. Can this be changed?

a. will update, may be related to android resource management.


3. Is it worth pursuing the original issue where it crashed very likely due to running out of memory?

a. If you can, let me know if reverting the memory usage back to what it was using before causes the crash, and then lowering the number to what you had it at before fixes it once again. This will let us confirm that the silent crash is indeed a resource issue.

Thanks for all your help @ThinkOpenly , I'll update this response with answers to your questions when I get accurate ones.

**Comment by ThinkOpenly** [comment]
I have a 12MB `PRoot_Debug_Log`.  It seems truncated, as if the messages were buffered and not flushed consistently.  I'm not sure how valuable it is.  Previously, @AdamMatthewLTM said "if a crash it detected it should automatically be sent to the playstore", but I'm guessing that did not happen.  I'm happy to send it or post it somewhere if it will help.  Here are the last few lines:
```
proot info: vpid 337: sysenter start: set_robust_list(0x725fffed20, 0x18, 0x725fffec40, 0x0, 0x7303819500, 0x428) = 0x725fffed20 [0x725fffe430, 0]
proot info: vpid 337: sysenter end: set_robust_list(0x725fffed20, 0x18, 0x725fffec40, 0x0, 0x7303819500, 0x428) = 0x725fffed20 [0x725fffe430, 0]
proot info: vpid 337: seccomp SIGSYS: set_robust_list(0x725fffed20, 0x18, 0x725fffec40, 0x0, 0x7303819500, 0x428) = 0x725fffed20 [0x725fffe430, 0]
proot info: vpid 337: sysenter start: rt_sigprocmask(0x2, 0x725fffe2b8, 0x725fffe338, 0x8, 0xfffffffe7fffffff, 0x1) = 0x2 [0x725fffe160, 0]
proot info: vpid 337: sysenter end: rt_sigprocmask(0x2, 0x725fffe2b8, 0x725fffe338, 0x8, 0xfffffffe7fffffff, 0x1) = 0x2 [0x725fffe160, 0]
proot info: vpid 337: sysexit start: rt_sigprocmask(0x0, 0x725fffe2b8, 0x725fffe338, 0x8, 0xfffffffe7fffffff, 0x1) = 0x0 [0x725fffe160, 0]
proot info: vpid 337: sysexit end: rt_sigprocmask(0x0, 0x725fffe2b8, 0x725fffe338, 0x8, 0xfffffffe7fffffff, 0x1) = 0x0 [0x725fffe160, 0]
proot info: vpid 338: pid 6827
proot info: vpid 338: seccomp SIGSYS: set_robust_list(0x7257ffed20, 0x18, 0x7257ffec40, 0x0, 0x7303819500, 0x428) = 0x7257ffed20 [0x7257ffe430, 0]
proot info: vpid 339: pid 6828
proot info: vpid 339: sysenter start: set_robust_list(0x72577fed20, 0x18, 0x72577fec40, 0x0, 0x7303819500, 0x428) = 0x72577fed20 [0x72577fe430, 0]
proot info: vpid 339: sysenter end: set_robust_list(0x72577fed20, 0x18, 0x72577fec40, 0x0, 0x7303819500, 0x428) = 0x72577fed20 [0x72577fe430, 0]
proot info: vpid 339: seccomp SIGSYS: set_robust_list(0x72577fed20, 0x18, 0x72577fec40, 0x0, 0x7303819500, 0x428) = 0x72577fed20 [0x72577fe430, 0]
proot info: vpid 339: sysenter start: futex(0x3000fb7ec0, 0x189, 0x0, 0x72577fe3c8, 0x0, 0xffffffff) = 0x3000fb7ec0 [0x72577fe2e0, 0]
proot info: vpid 339: sysenter end: futex(0x3000fb7ec0, 0x189, 0x0, 0x72577fe3c8, 0x0, 0xffffffff) = 0x3000fb7ec0 [0x72577fe2e0, 0]
proot info: vpid 339: sysexit start: futex(0x0, 0x189, 0x0, 0x72577fe3c8, 0x0, 0xffffffff) = 0x0 [0x72577fe2e0, 0]
proot info: vpid 339: sysexit end: futex(0x0, 0x189, 0x0, 0x72577fe3c8, 0x0, 0xffffffff) = 0x0 [0x72577fe2e0, 0]
proot info: vpid 15: sysenter start: openat(0xffffffffffffff9c, 0x300077e7b8, 0x0, 0x0, 0x0, 0x73027f2000) = 0xffffffffffffff9c [0x7fcd4a7a80, 0]
proot info: vpid 15: translate("/" + "/etc/resolv.conf")
proot info: vpid 15:          -> "/data/data/tech.ula/files/1/etc/resolv.conf"
proot info: vpid 15: sysenter end: openat(0xffffffffffffff9c, 0x7fcd4a7a54, 0x0, 0x0, 0x0, 0x73027f2000) = 0xffffffffffffff9c [0x7fcd4a7a54, 0]
proot info: vpid 15: sysexit start: openat(0xe, 0x7fcd4a7a54, 0x0, 0x0, 0x0, 0x73027f2000) = 0xe [0x7fcd4a7a54, 0]
proot i
```
It takes a LONG time for me to run the reproduce scenario, so I'm reluctant to do it over and over, but I can tell you that it failed identically 3 times in a row with qemu requesting 2GB; it worked when I reduced the memory requested as described previously (1.5GB), and it just failed again with the original memory request (2GB).

FYI, I'm using a Pixel 2, and just got notified to update to Android 9.  I'll see if that has any impact.

**Comment by ThinkOpenly** [comment]
Same crash happens on Android 9, with UserLAnd now updated to 0.3.4 (according to Play Store, or 0.3.3, according to App Info.  ??)

**Comment by corbinlc** [comment]
You currently have 0.3.3 .  When you get updated to 0.3.4 it is fixed.

**Comment by ThinkOpenly** [comment]
@corbinlc , I now have UserLAnd 0.3.4 (per the Play Store and App Info), and the failure still occurs.

**Comment by corbinlc** [comment]
Odd.  Must be a different memory issue.  We will look at our crash reports that we get from google.

**Comment by corbinlc** [comment]
Oh right.  Thinking of the wrong issue.  This is specific to running `qemu-system`.  I haven't tired that one.

**Comment by AdamMatthewLTM** [comment]
I am closing this thread for the following reason:

Android allows users to determine memory allocation for programs with the settings options, and qemu commandline programs take arguments to allocate specific memory usage as well. Because the android device itself seems to terminate a program that is trying to use more than its allocated memory, and does not produce any warnings, this is essentially the user's responsibility to ascertain what resources they should allocate to which processes. 

If anyone feels this thread should remain open, please explain your reasoning and I will re-open it ASAP. 

Thank you for your time and consideration in these matters,
-Adam
