### ISSUE TITLE
Appimage package does not start

### ISSUE THREAD

**Issue by planck2007** [CypherpunkArmory/UserLAnd#323]
Describe the bug
I downloaded Libreoffice in Appimage format and tried to run it. I changed the permissions to the file to make it executable, but when I run it a message says "file not found"

To Reproduce
1. download Libreoffice appimage package from here: https://libreoffice.soluzioniopen.com/stable/fresh/LibreOffice-fresh.basic-x86_64.AppImage

2. Open a terminal and go in the folder where the file has been downloaded

3. Add executable attributes: chmod a+x ./LibreOffice-fresh.basic-x86_64.AppImage

4. Try to execute the app: ./LibreOffice-fresh.basic-x86_64.AppImage

The console returns an error message: ./LibreOffice-fresh.basic-x86_64.AppImage: No such file or directory

Device: Samsung Galaxy Tab S3
Android Version: Oreo, 8.0
UserLAnd Version 0.5.0

**Comment by yunus70** [comment]
You can only run armhf based apps not x86_64.

**Comment by corbinlc** [comment]
Good call @yunus70 .  Also, I am not sure where you downloaded it to, but you need to get it inside the userland rootfs to be about the make it executable.  If it is on the sdcard, that is not executable.  So, please find the armhf image and please make sure it is no on the sdcard and try again.  I have not done exactly what you have done, but that will at least get you further.

**Comment by planck2007** [comment]
You are right and that was very naive of me. Unfortunately it seems that Libreoffice does not offer any armhf image, so there is no way I can test it unless I build an armhf-base image myself (which I doubt I have time and know-how to do). Unfortunately Libreoffice is not usable on Oreo because of issue #173 and I hoped the appimage were a good way around the problem.

**Comment by corbinlc** [comment]
I forgot to emulate /proc/version when dealing with some other /proc related files.  I will get back on that soon.

**Comment by AdamMatthewLTM** [comment]
@planck2007 ,

According to this link from a quick google search:

https://listarchives.libreoffice.org/global/users/msg21153.html

There should be some ports of LibreOffice for ARM. Can you go ahead and see if any of them work for you through debian? Please let me know if not or you run into issues.

Thanks,
-Adam

**Comment by corbinlc** [comment]
Libreoffice has been added as an app and #92 has been solved.  As such, the underlying issue is resolved.

**Comment by tommysllee** [comment]
Hi, are there any update on AppImage?
I wanted to run electrum-ltc.AppImage.. But the problem persisted
